// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyvzoxXZgj52f2tm2-lO8Zn6QgiblpFS0',
    appId: '1:816224154951:web:1bfbd88166fc3818ae4862',
    messagingSenderId: '816224154951',
    projectId: 'doodles-bb855',
    authDomain: 'doodles-bb855.firebaseapp.com',
    storageBucket: 'doodles-bb855.appspot.com',
    measurementId: 'G-ZJPLNVEZHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpMyIVk18F20SLqsODlOK3eL0WVrcOWNg',
    appId: '1:816224154951:android:74043a39f64941a5ae4862',
    messagingSenderId: '816224154951',
    projectId: 'doodles-bb855',
    storageBucket: 'doodles-bb855.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA54JO1yutONMVWZLcItrAQADdL8XiWVeI',
    appId: '1:816224154951:ios:5e1e42a60954fc47ae4862',
    messagingSenderId: '816224154951',
    projectId: 'doodles-bb855',
    storageBucket: 'doodles-bb855.appspot.com',
    iosClientId: '816224154951-tfivdio9lhsvc8avi78jac6ajc5h40oo.apps.googleusercontent.com',
    iosBundleId: 'com.example.doodles',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA54JO1yutONMVWZLcItrAQADdL8XiWVeI',
    appId: '1:816224154951:ios:f13cfe433d9e148bae4862',
    messagingSenderId: '816224154951',
    projectId: 'doodles-bb855',
    storageBucket: 'doodles-bb855.appspot.com',
    iosClientId: '816224154951-bcohd39g3nkqreemepllrnme9dgbrgph.apps.googleusercontent.com',
    iosBundleId: 'com.example.doodles.RunnerTests',
  );
}
